import asyncHandler from 'express-async-handler';
import { sendEmail } from '../utils/emailService.js';

// @desc    Submit contact form
// @route   POST /api/contact
// @access  Public
export const submitContactForm = asyncHandler(async (req, res) => {
  const { name, email, subject, message } = req.body;

  if (!name || !email || !subject || !message) {
    res.status(400);
    throw new Error('Please provide all fields');
  }

  // Send email to admin (the user)
  const adminEmail = process.env.EMAIL_USER;
  
  const emailSubject = `New Contact Query: ${subject}`;
  const emailText = `New message from ${name} (${email}):\n\n${message}`;
  const emailHtml = `
    <div style="font-family: Arial, sans-serif; color: #333; max-width: 600px; border: 1px solid #eee; padding: 20px; border-radius: 10px;">
      <h2 style="color: #2563eb;">📩 New Contact Query</h2>
      <p>You have received a new message from the <strong>DebtFree</strong> contact form.</p>
      <div style="background: #f8fafc; padding: 15px; border-radius: 8px; margin: 20px 0;">
        <p style="margin: 5px 0;"><strong>From:</strong> ${name} (${email})</p>
        <p style="margin: 5px 0;"><strong>Subject:</strong> ${subject}</p>
        <p style="margin: 5px 0;"><strong>Message:</strong></p>
        <p style="margin: 10px 0; font-style: italic;">${message}</p>
      </div>
      <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;" />
      <p style="font-size: 14px; color: #666;">This message was automaticaly generated by the DebtFree Backend.</p>
    </div>
  `;

  await sendEmail({
    to: adminEmail,
    subject: emailSubject,
    text: emailText,
    html: emailHtml,
    fromName: "DebtFree Contact Form"
  });

  res.status(200).json({ success: true, message: 'Message sent successfully' });
});
